name: "Pull Request Labeler"
on:
  # Run on the opened, synchronize, and reopened types of pull request actions
  pull_request_target:
    # If the following paths are being changed. 
    # Note this saves billable runs, but prevents us from using sync-labels: true
    paths:
      - 'migrate/*.sql'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false # Whether or not to remove labels when matching files are reverted or no longer changed by the PR
